# ============================================================
# Trabajo 3 - Caso A (flota)
#
#   localhost:9092 -> productor_flota.py (corre en Windows)
#   kafka:29092    -> Spark (corre en el contenedor 'spark')
# ============================================================

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  spark:
    image: apache/spark:3.5.3-python3
    container_name: spark
    user: root
    depends_on:
      - kafka
    working_dir: /app
    command: sleep infinity     # contenedor "vivo"; el detector se lanza con docker compose exec
    volumes:
      - ./:/app                 # esta carpeta de Windows aparece como /app dentro del contenedor
      - ivy_cache:/root/.ivy2   # guarda el conector spark-sql-kafka para no re-descargarlo

volumes:
  ivy_cache: